name: Version Update
run-name: ${{ github.actor }} is performing a version update.
on: 
  push:
    branches:
      - "main"
jobs:
  Version-Update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting version update step"
      - run: echo "Job started by ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run test:unit
      - run: npm run version:update