name: Version Update
run-name: ${{ github.actor }} is performing a version update.
on: 
  push:
    branches:
      - "main"
jobs:
  Version-Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Starting version update step"
      - run: echo "Job started by ${{ github.event_name }} event."
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.
      - name: Starting pipeline
        run: |
          npm ci
          npm run test:unit
          npm run version:update